---
- hosts: all
  remote_user: root
  tasks:
    - name: install Ruby-DEV
      apt: name=ruby-dev state=installed
    - name: install Ruby
      apt: name=ruby state=installed
    - name: install zlib1g-dev package
      apt: name=zlib1g-dev state=installed
    - name: install liblzma-dev package
      apt: name=liblzma-dev state=installed
    - name: install libssl-dev package
      apt: name=libssl-dev state=installed
    - name: install Github
      apt: name=git state=installed
    - name: pulling from Github
      git:
        repo: https://github.com/void269/Project-Erebus.git
        dest: "/etc/Project-Erebus"
        force: yes
        update: yes

- hosts: slave
  remote_user: root
  tasks:
    - name: install python
      apt: name=python-pip state=installed
    - name: install python ina219 package
      pip: name=pi-ina219
    - name: instal I2C tools
      apt: name=i2c-tools state=installed
    - name: enabling I2C
      command: raspi-config nonint do_i2c 0
    - name: rebooting
      command: shutdown -r now
      async: 1
      poll: 0
    - name: waiting for hosts to come back up
      wait_for_connection:
        args:
          delay: 15
          timeout: 120

- hosts: master
  remote_user: root
  tasks:
    - name: install Grafana
      apt: name=grafana state=installed
    - name: installing influxdb
      apt: name=influxdb state=installed
