---
- hosts: all
  remote_user: root
  tasks:
    - name: install Ruby-DEV
      apt: name=ruby-dev state=installed
    - name: install Ruby
      apt: name=ruby state=installed
    - name: install zlib1g-dev package
      apt: name=zlib1g-dev state=installed
    - name: install liblzma-dev package
      apt: name=liblzma-dev state=installed
    - name: install libssl-dev package
      apt: name=libssl-dev state=installed
    - name: install Github
      apt: name=git state=installed
    - name: pulling from Github
      git:
        repo: https://github.com/void269/Project-Erebus.git
        dest: "/etc/Project-Erebus"
        force: yes
        update: yes
    - name: setting update.sh to executable
      file:
        path: /etc/Project-Erebus/update.sh
        mode: a+x
    - name: setting start.sh to executable
      file:
        path: /etc/Project-Erebus/start.sh
        mode: a+x
    - name: creating erebus.conf directory
      file:
        path: /etc/erebus.conf
        state: directory
    - name: creating erebus/log directory
      file:
        path: /var/log/erebus
        state: directory
    - name: creating var/log/erebus directory
      file:
        path: /etc/erebus/logs
        state: directory
    - name: creating symlink
      file:
        scr: /var/log/erebus
        dest: /etc/erebus/logs
        state: link

- hosts: slave
  remote_user: root
  tasks:
    - name: creating slave file
      copy:
        content: ""
        dest: /etc/erebus.conf/slave
        force: no
        group: sys
        owner: root
        mode: 0555
    - name: install python
      apt: name=python-pip state=installed
    - name: install python ina219 package
      pip: name=pi-ina219
    - name: instal I2C tools
      apt: name=i2c-tools state=installed
    - name: checking if I2C s enabled
      shell: i2cdetect -y 1
      register: i2ccheck
    - name: enabling I2C
      command: raspi-config nonint do_i2c 0
      when: i2ccheck|failed
    - name: rebooting
      shell: shutdown -r +1
      when: i2ccheck|failed

- hosts: master
  remote_user: root
  tasks:
    - name: creating slave file
      copy:
        content: ""
        dest: /etc/erebus.conf/master
        force: no
        group: sys
        owner: root
        mode: 0555
    - name: install Grafana
      apt: name=grafana state=installed
    - name: installing influxdb
      apt: name=influxdb state=installed
    - name: installing rspec
      gem: name={{ item }} state=latest
      with_items:
        - rspec-core
        - rspec-expectations
        - rspec-mocks
