---
- hosts: slave
  sudo: yes
  remote_user: root
  tasks:
    - name: backup slave file
      copy:
        src: /etc/Project-Erebus/slave
        dest: /tmp/slave.bak

- hosts: master
  sudo: yes
  remote_user: root
  tasks:
    - name: backup master file
      copy:
        src: /etc/Project-Erebus/master
        dest: /tmp/master.bak

- hosts: all
  sudo: yes
  remote_user: root
  tasks:
    - name: pulling from Github
      git:
        repo: https://github.com/void269/Project-Erebus.git
        dest: /etc/Project-Erebus
        force: yes
        update: yes

- hosts: slave
  sudo: yes
  remote_user: root
  tasks:
    - name: checking if slave file is missing
      local_action: stat path="/etc/Project-Erebus/slave"
      register: slaveresult
    - name: copying back slave file if needed
      copy:
        src: /tmp/slave.bak
        dest: /etc/Project-Erebus/slave
        when: slaveresult|failed

- hosts: master
  sudo: yes
  remote_user: root
  tasks:
    - name: checking if master file is missing
      local_action: stat path="/etc/Project-Erebus/master"
      register: masterresult
    - name: copying back master file if needed
      copy:
        src: /tmp/master.bak
        dest: /etc/Project-Erebus/master
        when: masterresult|failed
