---
- hosts: all
  remote_user: root
  tasks:
    - name: pulling from Github
      git:
        repo: https://github.com/void269/Project-Erebus.git
        dest: /etc/Project-Erebus
        force: yes
        update: yes
